### ISSUE TITLE
Consider storing the tips in vimscript

### ISSUE THREAD

**Issue by h0adp0re** [michaelb/vim-tips#11]
I think it'd make this plugin more flexible to store the tips in vimscript. That way you can allow users to _add_ their own tips via configuration. Also this way you'd probably have cleaner code as well.

I'd be willing to help but I'm not proficient in vimscript nor python.

**Comment by michaelb** [comment]
Hi again, 
I don't think this is such a good idea.

I'm no stranger to vimscript performance issues, in addition to the strange syntax. 
I don't plan to make the plugin smart enough to be able to consistently display arbitrary tips; i'd rather have user dwelve into the files and understand the limitations of the framework (for example, no ' (single-quotes), length limit, utf8 only).

I don't want users to do `let g:vims_tips_add_this+=['tip = select all by  doing \'ggyG\'                                                         :smile: ']` because they won't be able to debug properly (because this particular tip will be displayed once every 200+ times) and it will either crash in a sea of red text or display inconsistently with the usual tips.


I didn't plan to spend too much time improving this plugin, it's supposed to 'just work', but you can of course fork/contribute

**Comment by h0adp0re** [comment]
Ah, I understand. No worries then, you can close this.
